name: build_vs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build_visual_studio_sln:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: create project
        run: |
          call create_visual_studio_project.bat
        shell: cmd

      - name: build
        run: |
          cd visual-studio
          cmake --build .
        shell: cmd

      - name: test
        run: |
          cd visual-studio
          ctest . -C debug
