name: build_vs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build_vs2019_sln:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1

      - name: create project
        run: |
          call create_visual_studio_project.bat
        shell: cmd

      - name: build
        run: |
          cd visual-studio-2019
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
          cmake --build .
        shell: cmd

      - name: test
        run: |
          cd visual-studio-2019
          ctest . -C debug
